# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FacilityLocation
                                 A QGIS plugin
 Dati un insieme di layer vettoriali di punti di clienti e di zone, e un intero k determina le k zone ottimali in cui costruire le facility.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-01-12
        copyright            : (C) 2021 by Peppe&Berni
        email                : peppe&berni@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load FacilityLocation class from file FacilityLocation.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .FacilityLocation import FacilityLocation
    return FacilityLocation(iface)
